### PR TITLE
Banner's Style.

### PR DESCRIPTION
**Pull request by peterp**
OLD:

screenshot 2016-04-13 10 35 45

NEW:
screenshot 2016-04-13 10 34 18

### CODE REVIEW

**Comment by peterp** [comment]
Maybe I should merge some of these changes into molo-core.

**Comment by hodgestar** [comment]
The less stuff outside of molo-core the better.

**Comment by peterp** [comment]
@hodgestar I made changes `template-base.css` which, as I understand it, is copied from molo's core into projects.

**Comment by smarzban** [comment]
👍

**Pull request merged**
