### PR TITLE
style comments preview page

### PR DESCRIPTION
**Pull request by codiebeulaine**

### CODE REVIEW

**Comment by smarzban** [comment]
@codiebeulaine please add a screenshot

**Comment by codiebeulaine** [comment]
screen shot 2016-07-14 at 4 55 18 pm

**Comment by smarzban** [comment]
@codiebeulaine can you fix the padding around the error message

**Comment by codiebeulaine** [comment]
screen shot 2016-07-14 at 6 15 35 pm

**Comment by smarzban** [comment]
👍

**Pull request merged**
