### PR TITLE
Update polls templates to latest 

### PR DESCRIPTION
**Pull request by smarzban**

### CODE REVIEW

**Comment by smarzban** [comment]
@miltontony ready for review :)

**Comment by miltontony** [comment]
hmm...I'm not too happy with doing this `value="{{ choice.get_main_language_page.id }}"` - we should do that in the view so that it doesn't matter if a user votes against `choice.id`, the vote will always get allocated to `choice.get_main_language_page.id`
I'll create an issue on `molo.polls`

**Comment by miltontony** [comment]
:+1:

**Comment by miltontony** [comment]
https://github.com/praekelt/molo.polls/issues/6

**Pull request merged**
